apiVersion: v1
kind: Service
metadata:
  name: booking
  namespace: servicecomb
  labels:
    app: scsaga-booking
spec:
  ports:
  - port: 8083
    targetPort: 8080
    name: booking
  selector:
    app: scsaga-booking
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: scsaga-booking
  namespace: servicecomb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: scsaga-booking
        version: v1
    spec:
      containers:
      - name: scsaga-booking
        image: booking:0.3.0-SNAPSHOT
        imagePullPolicy: IfNotPresent
        env:
        - name: JAVA_OPTS
          value: -Dalpha.cluster.address=alpha-server.servicecomb:8080 -Dcar.service.address=http://car.servicecomb:8082 -Dhotel.service.address=http://hotel.servicecomb:8081
        ports:
        - containerPort: 8080
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: booking-nodeip
#   namespace: servicecomb
#   labels:
#     app: scsaga-booking
# spec:
#   type: NodePort
#   ports:
#   - port: 8088
#     # targetPort: 8088
#     name: http
#   externalIPs: ['192.168.43.70']
#   selector:
#     app: scsaga-booking
# ---
