apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: car-all-v1
  namespace: servicecomb
spec:
  hosts:
  - car.servicecomb.svc.cluster.local
  http:
  - route:
    - destination:
        host: car.servicecomb.svc.cluster.local
        subset: car-v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: car-rules
  namespace: servicecomb
spec:
  host: car.servicecomb.svc.cluster.local
  subsets:
  - labels:
      version: v1
    name: car-v1
